### ISSUE TITLE
US 03.03.01 (Bar code for trial)

### ISSUE THREAD

**Issue by PileUp120** [CMPUT301W21T28/trialio#11]
US 03.03.01
As an experimenter, I want to be able to register an arbitrary bar code (such as one off of your favourite book) to act a specific experiment result for a trial.

Rationale: So that the experimenter can reduce the amount of interactions they have to do to participate in a trial, and still contribute to the experiments with ease.
Story Points: 20
Risk level: High

**Comment by debecerra** [comment]
#### Clarifications 

- Registered bar codes should be private to the user that created them.
- Registered bar codes should have the option to be removed.

**Comment by debecerra** [comment]
https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1662116#p4370978

**Comment by debecerra** [comment]
This is good now
