### ISSUE TITLE
US 05.01.01 (Search by keyword) 

### ISSUE THREAD

**Issue by debecerra** [CMPUT301W21T28/trialio#14]
US 05.01.01
As an experimenter, I want to specify a keyword, and search for all experiments that are available.

Rationale: Want to be able to find experiments quickly, even when there are lots of experiments and want to be able to find available experiments easily. 
Story Points: 15 
Risk Level: High

**Comment by victorsmith** [comment]
Query language seems to be fairly straightforward:
https://firebase.google.com/docs/firestore/query-data/queries
