### ISSUE TITLE
App crashes when retrieving Users via an id of NULL 

### ISSUE THREAD

**Issue by debecerra** [CMPUT301W21T28/trialio#150]
### Cause:
 - ArrayAdapterExperiment fetching User via the owner IDs of a collection of experiments
 - One of the experiments had a NULL value for its experiment ID, causing a Firebase crash

### Solution: 
- Add error handling so that null values can't be queried using UserManager
- Investigate why an experiment was able to be created without an owner

**Comment by quinnlp** [comment]
dublicate
