### ISSUE TITLE
re draw ui plan for part 4

### ISSUE THREAD

**Issue by victorsmith** [CMPUT301W21T28/trialio#197]

**Comment by victorsmith** [comment]
UI plan has to be updated before final assessment deadline

**Comment by quinnlp** [comment]
Update storyboard to reflect part 4 changes. Also need to make it easier to read, easier to find particular user stories, space things out. -Diego

**Comment by victorsmith** [comment]
Submitted for review in google chat. Last-minute changes might be made if Alex requests them.

**Comment by debecerra** [comment]
Looks really good. I just wanted to comment that since major changes were made, it would be a good idea to go through all the user stories and make sure they are all present in the new UI mockup (in this hasn't been done already)
