### ISSUE TITLE
US 06.03.01 (Warning for geo-location trials)

### ISSUE THREAD

**Issue by yuchieh8968** [CMPUT301W21T28/trialio#24]
US 06.03.01
As an experimenter, I want to be warned about geo-location trials.

Rationale: So that experimenters will be aware that locations exist in the trials experimenters selected.
Story Points: 5
Risk Level: Low

**Comment by victorsmith** [comment]
Location tracking must be consensual for ethical and legal reasons. Check privacy laws in other countries (especially EU)
