### ISSUE TITLE
US 06.04.01  (Map of geo-location)

### ISSUE THREAD

**Issue by yuchieh8968** [CMPUT301W21T28/trialio#25]
US 06.04.01
As an experimenter, I want to see a map of geo-locations of a geo-location enabled experiment.

Rationale: So that experimenters can visualize where trials where performed for a geo-location experiment.
Story Point: 20
Risk Level: High

**Comment by victorsmith** [comment]
Location tracking must be consensual for ethical and legal reasons. Check privacy laws in other countries (especially EU)
