### ISSUE TITLE
Plots only showing up after 2 clicks has returned

### ISSUE THREAD

**Issue by ryanjacquess** [CMPUT301W21T28/trialio#255]
And I am confounded. The code Quinn wrote remains unchanged but it doesn't seem to work anymore

**Comment by ryanjacquess** [comment]
Never mind... I think my emulator was just being funky and messing with me? But there is a separate similar issue, which I also confirmed on my phone: time plot for non-negative experiment, and likely binomial/measurement too, does not show up first time but does the second time. Probably the exact same issue with both of them not initially showing up

**Comment by debecerra** [comment]
I think the issue still exists
![image](https://user-images.githubusercontent.com/47841864/114223319-e684b680-992c-11eb-849a-942f1625be06.png)
![image](https://user-images.githubusercontent.com/47841864/114223345-f0a6b500-992c-11eb-9a1e-970abe4dcc6b.png)

**Comment by debecerra** [comment]
I think I found a fix though https://github.com/PhilJay/MPAndroidChart/issues/88#issuecomment-55651698
```
  histogram.setData(data);
  histogram.invalidate(); // new line
```

**Comment by debecerra** [comment]
I know you've been working in StatActivity.java, so I'm hesitant to make changes to that file myself. Can you check this and see if (a) it fixes the issue on your end and (b) can you make it part of your existing PR if you have one? @ryanjacquess

**Comment by debecerra** [comment]
> Never mind... I think my emulator was just being funky and messing with me? But there is a separate similar issue, which I also confirmed on my phone: time plot for non-negative experiment, and likely binomial/measurement too, does not show up first time but does the second time. Probably the exact same issue with both of them not initially showing up

I think it's the same issue as all of these. Probably a synchronization issue where it would sometimes load properly and show if you ran it slowly with the debugger. Not sure but that's my guess.
