### ISSUE TITLE
US 01.06.01 (Histogram)

### ISSUE THREAD

**Issue by quinnlp** [CMPUT301W21T28/trialio#26]
US 01.06.01
As an owner or experimenter, I want to see histograms of the results of trials.

Rationale: So that the owner and experimenter can observe their results in a visual histogram form.
Story Points: 10
Risk Level: Medium

**Comment by debecerra** [comment]
### Clarification:

Show me the proportions of answers, not meaningful for count, but meaningful for binomial and non-negative and measurement.

**Comment by ryanjacquess** [comment]
All finished with this user story!
