### ISSUE TITLE
US 01.07.01 (Plots)

### ISSUE THREAD

**Issue by quinnlp** [CMPUT301W21T28/trialio#27]
US 01.07.01
As an owner or experimenter, I want to see plots of the results of trials over time.

Rationale: So that the owner and experimenter can view how the results of an experiment have changed over time in a visual form.
Story Points: 20
Risk Level: High

**Comment by debecerra** [comment]
### Clarification

* Binomial: show the proportion of success over time
* Count: show count increase over time
* Non-negative: show mean over time? Quantiles over time?
* Measurement: show mean over time? Quantiles over time?
