### ISSUE TITLE
US 01.01.01 (Publish experiments)

### ISSUE THREAD

**Issue by quinnlp** [CMPUT301W21T28/trialio#4]
US 01.01.01
As an owner, I want to publish an experiment with a description, a region, and a minimum number of trials.

Rationale: So that owners can create experiments that they want to conduct.
Story Points: 5
Risk Level: Low

**Comment by debecerra** [comment]
#### Clarification: 

A region can just be a textual description of where it should be done. You should allow for a bit of writing to go there or a geolocation and a radius.

Description: Count all Red Cardinals in Edmonton
Geolocation: Greater Edmonton Area

Description: Count littered flyers and leaflets
Geolocation: 53.52667785793429, -113.52644318267107
