### ISSUE TITLE
US 01.02.01 (Unpublish experiments)

### ISSUE THREAD

**Issue by quinnlp** [CMPUT301W21T28/trialio#5]
US 01.02.01
As an owner, I want to unpublish an experiment.

Rationale: So that owners can remove experiments that they do not want anymore. For example, if they felt that the conditions for the experiment were faulty, or lead to unfair biases
Story Points: 3
Risk Level: Low

**Comment by debecerra** [comment]
#### Clarification 
- To "unpublish an experiment" means it is not publicly available to view or interact with.
