### ISSUE TITLE
US 01.04.01 (Subscribe to experiments)

### ISSUE THREAD

**Issue by quinnlp** [CMPUT301W21T28/trialio#7]
US 01.04.01
As an owner or experimenter, I want to subscribe to an experiment to participate in it.

Rationale: So that both owners and experimenters can keep track of experiments that interest them and experiments they want to participate in.
Story Points: 10
Risk Level: Medium

**Comment by debecerra** [comment]
#### Clarifications 
- Subscriptions are just a way for experimenters to pay attention to experiments and easily access them (like bookmarks). It is not a special status
- Subscriptions is local to a users device and not necessary for a user to participate in an experiment
- Users should be automatically subscribed if they add a trial to an experiment
