### ISSUE TITLE
Create a method to get the current user FID

### ISSUE THREAD

**Issue by quinnlp** [CMPUT301W21T28/trialio#72]
So that it can be used when creating Trials.

**Comment by debecerra** [comment]
I think the better way to do this would be to get the current user then `currentUser.getId()`. We don't really need anything other than the internals of UserManager knowing about FIDs. What do you think? Would this accomplish what you need it to do? @quinnlp

**Comment by debecerra** [comment]
I can work on that one-time user fetch functionality if that's needed
