### ISSUE TITLE
App crashes on experiment selection 

### ISSUE THREAD

**Issue by debecerra** [CMPUT301W21T28/trialio#73]
#### Priority:
**High**

#### Description:

The entire app crashes when selecting an experiment from main activity. To replicate this, start the app, select an experiment, go back to main screen, select an experiment again. It crashes on the second attempt. I suspect this has to do with how we manage our adapters and ExperimentManager

#### Log messages :
```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.example.trialio.Experiment)

```

**Comment by quinnlp** [comment]
Resolved. Location wasn't implementing serializable.
