### ISSUE TITLE
US 01.05.01 (Execute and upload trials)

### ISSUE THREAD

**Issue by quinnlp** [CMPUT301W21T28/trialio#8]
US 01.05.01
As an experimenter, I want to be able to execute trials for an experiment and upload them to the experiment.

Rationale: So that experimenters can contribute their results to experiments.
Story Points: 10
Risk Level: Medium

**Comment by debecerra** [comment]
#### Clarification 
- Experimenters should be able to add trials offline such that the trials will be uploaded when online again

**Comment by debecerra** [comment]
Practically done, a minor refactoring could be done but the interface works as intended
