### ISSUE TITLE
Refactor Experiments in Firebase so that Trials are stored in a collection

### ISSUE THREAD

**Issue by quinnlp** [CMPUT301W21T28/trialio#87]

**Comment by debecerra** [comment]
Adding extra notes to this item: 
 - The idea is that eventually the trials could be stored as a subcollection of experiment
 - This would allow for much more concise, simple experiment documents that needed to be stored in Firestore 
    - `extractExperiment()` could be heavily refactored (see `UserManager#extractUser` for ideas)
 - Would also make it less expensive to fetch experiment documents and watch for updates
 - This will become necessary for experiments with large amounts of trials
