### ISSUE TITLE
US 03.01.01 (Generate QR code)

### ISSUE THREAD

**Issue by PileUp120** [CMPUT301W21T28/trialio#9]
US 03.01.01
As an experimenter, I want to be able to generate QR codes that I can print for a specific experiment and trial result (for instance PASS for a binomial trial I subscribed to). 

Rationale: So that an experimenter can make an easy method of recording trial results.
Story Points: 15
Risk level: High

**Comment by quinnlp** [comment]
a QR code is unique by trial result & experiment

experiment1 BINOMIAL trueQR falseQR

experiment2 NONNEGATIVE 0QR, 1QR, 2QR, ...

experiment3 COUNT 1QR

experiment4 MEASUREMENT 0.01QR, 0.02QR, ...
