### ISSUE TITLE
Mar 14 tasks Try for Friday!

### ISSUE THREAD

**Issue by quinnlp** [CMPUT301W21T28/trialio#91]
- [x] publish experiments [Ryan]
- [x] unpublish experiments [Quinn]
- [x] Ending experiments [Quinn]
- [x] subscriptions [Diego]
- [x] MainPage toggle [Diego]
- [x] owned experiments (toggle)[Diego]
- [x] experiment owner settign UI [Mohammed]
- [x] location/geolocation (ask permission) [Mohammed]
- [x] edit profile [Jeff]
- [x] start looking into QR codes [Jeff]
- [x] correctly display trial info [Jeff]
- [x] continue working on question forum [Victor]
- [x] User search
- [x] Experiment search []
- [ ] generate unique username for each user, and enforce uniqueness []

**Comment by debecerra** [comment]
Don't need user search right now, just need a way to select an experimenter or an owner and see their profile information
